import sampleSize from 'lodash/sampleSize'
import urljoin from 'url-join'

import { MEDIA_CDN } from '../../constants'
import { Media, MediaConfig } from '../../types'

const getMediaUrl = (path: string) => urljoin(MEDIA_CDN, path)

const mapMediaConfigToMedia = (mediaConfig: MediaConfig): Media => {
  const folder = mediaConfig.type === 'video' ? 'videos' : 'images'
  const src = getMediaUrl(`/rodai-media/${folder}/${mediaConfig.fileName}`)
  return {
    ...mediaConfig,
    src,
  }
}

export const getRandomizedMedia = (count: number = 50): Media[] => {
  return sampleSize(mediaConfig, count).map(mapMediaConfigToMedia)
}

const mediaConfig: MediaConfig[] = [
  {
    fileName: '5-million-rod.webm',
    type: 'video',
    width: 512,
    height: 512,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'ai-rod-blinking.webm',
    type: 'video',
    width: 1920,
    height: 1080,
    aspectRatio: '16 / 9',
  },
  {
    fileName: 'ai-rod-closeup.webm',
    type: 'video',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'ai-rod-flying-high.webm',
    type: 'video',
    width: 1920,
    height: 1080,
    aspectRatio: '16 / 9',
  },
  {
    fileName: 'ai-rod-middle.webm',
    type: 'video',
    width: 1920,
    height: 1080,
    aspectRatio: '16 / 9',
  },
  {
    fileName: 'ai-rod-through-ranks.webm',
    type: 'video',
    width: 1920,
    height: 1080,
    aspectRatio: '16 / 9',
  },
  {
    fileName: 'break-ath.webm',
    type: 'video',
    width: 512,
    height: 512,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'break-bag-rod.webm',
    type: 'video',
    width: 768,
    height: 768,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'buy-buy.webm',
    type: 'video',
    width: 512,
    height: 512,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'may-the-rod-be-with-you.webm',
    type: 'video',
    width: 512,
    height: 512,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'rodcinerator-buning.webm',
    type: 'video',
    width: 848,
    height: 848,
    aspectRatio: '1 / 1',
  },
  {
    fileName: '1billion-rod-fireworks.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: '1billion-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: '1billion-rod09834.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'american-rod1.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'american-rod2.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'artist-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'astronaut-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'astronaut-rod239032.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'bagpack-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'beach-chillin-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'beach-massage-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'bearish-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'bota-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'break-ath.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'breakpoint-2024.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'brogrammer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'builder-rod1.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'builder-rod2.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'bullish-rod2.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'centurion-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'chad-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'chart-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'chart-rod133412.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'chef-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'chulo-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'clockmaker-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'clown-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'coffee-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'confused-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'creepy-clown-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'creepy-halloween-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'crypto-ken-rod2.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'crypto-ken-rod4.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'crypton-ken-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'dca-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'deep-dish-pizza-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'detective-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'dj-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'doctor-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'election-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'explorer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'f1rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'farmer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'fireman-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'fishing-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'galaxy-shades-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'garden-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'gecko-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'gm-rod-3794j.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'gm-rod1.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'gm-say-it-back-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'going-up-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'goku-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'green-gm-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'green-rocket-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'gta-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'halloween-rod-84723.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'halloween-rod1.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'halloween-rod3.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'halloween-rod9.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'halo-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'happy-ireland-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'hip-hop-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'hodl-camel-rod.webp',
    type: 'image',
    width: 1792,
    height: 1024,
    aspectRatio: '7 / 4',
  },
  {
    fileName: 'hot-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'ireland-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'ireland-rod4.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'king-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'kingday-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'kungfu-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'lab-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'launchpad-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'love-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'love-rod23902.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'm2-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'martial-arts-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'meditating-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'meeting-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'mexican-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'mimosa-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'mini-rod.webp',
    type: 'image',
    width: 1280,
    height: 1280,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'money-printer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'morning-coffee-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'ninja-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'nothing-here-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'obi-wan-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'painter-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'pie-chart-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'pilgrim-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'pilot-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'police-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'programmer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'rod-in-a-bag.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'rodai-pfp.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'roman-centurion-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'sagrada-familia-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'samurai-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'santa-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'scuba-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'sexy-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'skater-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'soccer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'solana-rod3028342.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'solana-smile-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'something-is-coming-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'strong-boxer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'strong-gm-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'strong-surfer-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'super-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'telescope-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'titanic-rod.webp',
    type: 'image',
    width: 1280,
    height: 853,
    aspectRatio: '1280 / 853',
  },
  {
    fileName: 'toly-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'trump-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'tumbler-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'turkey-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'twitter-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'viking-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'wifey-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'wine-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
  {
    fileName: 'wizard-rod.webp',
    type: 'image',
    width: 1024,
    height: 1024,
    aspectRatio: '1 / 1',
  },
]
